sudo: required
services:
- docker
language: go
install:
- go run ci.go $([ -z ${TEST_TAG} ] || echo "--tag ${TEST_TAG}")
script:
- if ! [ -z ${TEST_TAG} ]; then git checkout ${TEST_TAG}; fi
- go test -v
branch:
  only:
  - master

matrix:
  include:
  - env: TEST_TAG=latest
  - env: TEST_TAG=alpine
  - env: TEST_TAG=10.3-alpine
  - env: TEST_TAG=10.3
  - env: TEST_TAG=9.6.8-alpine
  - env: TEST_TAG=9.6.8
  - env: TEST_TAG=9.5.12-alpine
  - env: TEST_TAG=9.5.12
  - env: TEST_TAG=9.4.17-alpine
  - env: TEST_TAG=9.4.17
  - env: TEST_TAG=9.3.22-alpine
  - env: TEST_TAG=9.3.22
  - env: TEST_TAG=9.2.23-alpine
  - env: TEST_TAG=9.2.23
  - env: TEST_TAG=9.1.24
  - env: TEST_TAG=9.0.22
  - env: TEST_TAG=9-alpine
  - env: TEST_TAG=9
  - env: TEST_TAG=8.4.22
  - env: TEST_TAG=8
